image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - setupCI

build: off  # будем использовать свой скрипт сборки

install:
  - chmod +x gradlew
  - java -jar ./artifacts/app-card-delivery.jar &

build_script:
  - ./gradlew test -Dselenide.headless=true
  - ./gradlew test --info
